name: Run staticcheck on a Go module

description: Run staticcheck static analysis on a Go module

inputs:
  path:
    description: Path to the module
    required: true
    default: .

  go-version:
    description: Version of Go to target
    required: true
    default: "1.15" # TODO: change to "module" when https://github.com/dominikh/go-tools/commit/c5ce990a4e39053fda5229d7ac0877c5d78dd84d is released

  staticcheck-version:
    description: Version of staticcheck to run
    required: true
    default: latest

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        docker_image="ghcr.io/zencargo/staticcheck:${{ inputs.staticcheck-version }}"
        docker pull "${docker_image}" >/dev/null

        go_pkg_mod="${HOME}/go/pkg/mod"
        mkdir -p "${go_pkg_mod}"

        gid=$(id -g)

        docker run \
          --env XDG_CACHE_HOME=/tmp \
          --mount type="bind",source="${go_pkg_mod}",target="/go/pkg/mod" \
          --mount type="bind",source="${GITHUB_WORKSPACE}",target="/workspace" \
          --rm \
          --user "${UID}:${gid}" \
          --workdir "/workspace/${{ inputs.path }}" \
          "${docker_image}" \
          -f stylish \
          --go "${{ inputs.go-version }}" \
          ./...
