name: test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Test with unproblematic Go module
        uses: ./
        with:
          path: test/good

      - name: Test with problematic Go module
        id: bad
        continue-on-error: true
        uses: ./
        with:
          path: test/bad

      - name: Check that problematic Go module failed
        run: test "${{ steps.bad.outcome }}" = "failure"
